repos:
  -   repo: https://github.com/doublify/pre-commit-rust
      rev: master
      hooks:
        -   id: fmt
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
        -   id: check-json
        -   id: check-yaml
        -   id: trailing-whitespace
        -   id: mixed-line-ending
        -   id: pretty-format-json
            args: [ "--no-sort-keys", "--autofix" ]

