[package]
name = "graphene_api"
version = "0.1.0"
authors = ["Rafał Wojdyła <omeg@invisiblethingslab.com>"]
edition = "2018"

[lib]
name = "graphene"
path = "src/lib.rs"

[[bin]]
name = "graphene_test"
path = "src/bin.rs"

[dependencies]
sgx_types = "1.1"
byteorder = "1.3"
